sudo: required
language: node_js

node_js:
  - 12

before_install:
  - npm install -g yarn

before_script:
  # where is Cypress binary cached?
  - yarn cypress cache path
  # show me all versions of Cypress binary cached
  - yarn cypress cache list
  - yarn cypress verify

dist: trusty
cache:
  directories:
    - $HOME/.cache

addons:
  chrome: stable

notifications:
  email: false

defaults: &defaults
  script:
    - commitlint-travis
    - npm run ci

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME=4x-chrome
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-chrome
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-chrome
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-chrome
      <<: *defaults
    - stage: deploy
      if: branch = master
      script:
        - npm run build:prerender-ghpages
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist/browser
        github_token: $GH_TOKEN
        on:
          branch: master
