sudo: required
language: node_js

node_js:
  - 12

dist: trusty
cache: yarn

addons:
  chrome: stable

branches:
  only:
    - master

notifications:
  email: false

defaults: &defaults
  script:
    - commitlint-travis
    - npm run ci

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/browser
  github_token: $GH_TOKEN
  on:
    branch: master
